### ISSUE TITLE
rails 3.2

### ISSUE THREAD

**Issue by mikdiet** [puffer/puffer#39]
Hello,
I make quick patches for puffer to work with rails 3.2

https://github.com/morsbox/puffer/commits/master

May be something else, I don't run specs :)

**Comment by ghost** [comment]
I got an error
I just created a resource 

```
rails g puffer:controller User
```

And the routes

```
namespace :admin do
  resources :users
end
```

But I have this error, using this patch :

   undefined method `to_adapter' for nil:NilClass

I use rails 3.2.0 and default Mongoid.

**Comment by pyromaniac** [comment]
Try to define mongoid before puffer in your Gemfile.

**Comment by pyromaniac** [comment]
Немного не так, но сделал. Спасибо.

**Comment by monomadic** [comment]
@pyromaniac that doesn't work and I don't see how it would make any difference.

**Comment by pyromaniac** [comment]
I'll try to dig deeper. How should it help?  It is an orm_adapter feature. https://github.com/ianwhite/orm_adapter/blob/master/lib/orm_adapter.rb#L19 - right here. As you can see, adapter try to check Mongoid::Document existance. Bundler makes require in the same order as specified at Gemfile. Puffer requires orm_adapter explicitly, so if mongoid will be required after puffer, orm_adapter will not require orm_adapter/adapters/mongoid and we will get undefined method `to_adapter'

**Comment by Papipo** [comment]
I think that what is nil is PufferUser. Try renaming your User related stuff to PufferUser, or configure Puffer to use User instead.

**Comment by pyromaniac** [comment]
Maybe, you can publish full stacktrace? So i can reproduce error locally and fix it.

**Comment by krim** [comment]
Без монгойда, рельсы 3.2.2
NoMethodError in Admin::NewsCategoriesController#index

undefined method `to_adapter' for nil:NilClass

puffer (0.1.1) lib/puffer/resource.rb:96:in `adapter'
puffer (0.1.1) lib/puffer/resource.rb:102:in`collection'
puffer (0.1.1) lib/puffer/backends/controllers/base.rb:17:in `index'
actionpack (3.2.2) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.2.2) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.2) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.2.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.2) lib/active_support/callbacks.rb:425:in`_run__716298387__process_action__678247525__callbacks'
activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.2) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
activesupport (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.2) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.2) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.2.2) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.2) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.2) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.2) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.2.2) lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
activerecord (3.2.2) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
puffer (0.1.1) lib/puffer/controller/mutate.rb:15:in `process_action'
actionpack (3.2.2) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.2.2) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.2) lib/action_controller/metal.rb:203:in`dispatch'
actionpack (3.2.2) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.2) lib/action_controller/metal.rb:246:in`block in action'
actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in `call'
actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in`dispatch'
actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:30:in `call'
journey (1.0.3) lib/journey/router.rb:68:in`block in call'
journey (1.0.3) lib/journey/router.rb:56:in `each'
journey (1.0.3) lib/journey/router.rb:56:in`call'
actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:594:in `call'
actionpack (3.2.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
rack (1.4.1) lib/rack/etag.rb:23:in `call'
rack (1.4.1) lib/rack/conditionalget.rb:25:in`call'
actionpack (3.2.2) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.2) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.1) lib/rack/session/abstract/id.rb:205:in`context'
rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
flash_cookie_session (1.1.3) lib/flash_cookie_session/middleware.rb:18:in`call'
actionpack (3.2.2) lib/action_dispatch/middleware/cookies.rb:338:in `call'
activerecord (3.2.2) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `_run__142447533__call__681897886__callbacks'
activesupport (3.2.2) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.2) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.2) lib/action_dispatch/middleware/reloader.rb:65:in`call'
actionpack (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.2) lib/rails/rack/logger.rb:26:in`call_app'
railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in`call'
rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.1) lib/rack/runtime.rb:17:in`call'
activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.1) lib/rack/lock.rb:15:in`call'
actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
railties (3.2.2) lib/rails/engine.rb:479:in`call'
railties (3.2.2) lib/rails/application.rb:220:in `call'
railties (3.2.2) lib/rails/railtie/configurable.rb:30:in`method_missing'
rack (1.4.1) lib/rack/lint.rb:48:in `_call'
rack (1.4.1) lib/rack/lint.rb:36:in`call'
rack (1.4.1) lib/rack/showexceptions.rb:24:in `call'
rack (1.4.1) lib/rack/commonlogger.rb:20:in`call'
rack (1.4.1) lib/rack/chunked.rb:43:in `call'
rack (1.4.1) lib/rack/content_length.rb:14:in`call'
unicorn (4.2.0) lib/unicorn/http_server.rb:530:in `process_client'
unicorn (4.2.0) lib/unicorn/http_server.rb:604:in`worker_loop'
unicorn (4.2.0) lib/unicorn/http_server.rb:487:in `spawn_missing_workers'
unicorn (4.2.0) lib/unicorn/http_server.rb:137:in`start'
unicorn (4.2.0) bin/unicorn:121:in `<top (required)>'
/var/www/rbw_app/shared/.gems/ruby/1.9.1/bin/unicorn:19:in`load'
/var/www/rbw_app/shared/.gems/ruby/1.9.1/bin/unicorn:19:in `<main>'

**Comment by krim** [comment]
Так же заходе на /admin
NoMethodError in Admin/dashboard#index

Showing /var/www/rbw_app/shared/.gems/ruby/1.9.1/gems/puffer-0.1.1/app/views/puffer/dashboard_base/index.html.erb where line #8 raised:

undefined method `model_name' for nil:NilClass

Extracted source (around line #8):

5:       <li>
6:         <span><%= group.to_s.humanize %></span>
7:         <ul class="additional">
8:           <% puffer_resources_navigation scope, group do |resource, url| %>
9:             <li>
10:               <%= link_to resource, url %>
11:             </li>

Возможно как-то относится к этому....

**Comment by proton** [comment]
On opening /admin/
undefined method `to_adapter' for nil:NilClass

rails 3.2.2, mongoid, puffer
Mongoid defined before puffer in Gemfile.

P.S. pyromaniac, помоги мне!

**Comment by pyromaniac** [comment]
С удовольствием помогу. Давай так, ты сделаешь щас bundle update, убедившись, что паффер берётся из гита, и посмотришь снова ошибку, изменилась ли она. Если нет - то вываливаешь мне сюда полный бэктрейс.

**Comment by proton** [comment]
Видимо побираюсь ближе к проблеме, ошибки появились после переезда с ActiveRecord на Mongoid.
Обнаружил в ошибках упоминание current_user, удалил контроллер PufferUser, попытался перегенерить и облом:
https://gist.github.com/2174685

**Comment by proton** [comment]
А /admin/ после удаления контроллера выдаёт:

```
    Puffer controller can not found model named PufferUser
    To solve this you should properly configurate controller

    class Admin::SessionsController
      setup do
        model_name 'your_custom_model_name'
      end
    end
```

**Comment by pyromaniac** [comment]
О, здорово. Я примерно понимаю, в чём дело. Щас разберёмся.
А скажи мне, чего ты вообще хочешь там? Система авторизации какая планируется?

**Comment by proton** [comment]
Да пофиг вообще, там почти сайт-визитка, так что учётная запись скорее всего будет одна :)

**Comment by pyromaniac** [comment]
Кароче, я сраного PufferUser вынес в генератор. С ним слишком много проблем. Дальше - я добавил в ридмик небольшое объяснение по поводу авторизации. Обнови гем ещё раз и почитай объяснение - я его сюда скопирую

Post-installation actions.
First of all, it is nessesary to create security system for admin interface. It consists of two parts: user model and sessions controller. There are two cases for it:

Integrated auth system

Simple integarted auth system. To activate it - just execute rails g puffer:puffer_user. This will create model, migrations, controller and routes for PufferUser model. Also, default sessions controller which uses PufferUser model already in engine. So, both parts of auth system are ready for usage. Also there is mongoid backend for PufferUser storage. See app/models/puffer_user.rb for details.

External auth system

If application already use some kind of auth system like a devise, clearance or sorcery - you should use corresponding SessionsController backend. Just create app/controllers/admin/sessions_controller.rb in your application directory to redefine default SessionsController.

The content of file depends on used auth system. There are several backends for SessionsController exists in Puffer. I.e. for clearance use:

class Admin::SessionsController < Puffer::Sessions::Clearance
end
See https://github.com/puffer/puffer/tree/master/lib/puffer/backends/controllers/sessions for the list of backends. Also you can create your own backend.

If you use app's auth system, you might want to redefine access rules. The simpliest way for it - is to redefine current_puffer_use or has_puffer_access? methods in controller or implement has_role? method for your user model. See https://github.com/puffer/puffer/blob/master/lib/puffer/controller/auth.rb for details.

Как я понимаю, если у тебя всё просто - то лучше тебе юзать первый вариант. Но ты ознакомься, чтобы понимать в целом и оценить объяснение, достаточно ли такого, всё ли понятно?

**Comment by proton** [comment]
У меня плохие новости:

proton@earth onila % rails g puffer:puffer_user                                                                                                                                                                               (11:33)
DEPRECATION WARNING: ActiveSupport::Memoizable is deprecated and will be removed in future releases,simply use Ruby memoization pattern instead. (called from <top (required)> at /home/proton/projects/onila/config/application.rb:11)
/home/proton/.rvm/gems/ruby-1.9.3-p0@onila/bundler/gems/puffer-4b18186e8916/lib/generators/puffer/puffer_user/puffer_user_generator.rb:6:in `next_migration_number': uninitialized constant Puffer::PufferUserGenerator::ActiveRecord (NameError)
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/railties-3.2.2/lib/rails/generators/migration.rb:49:in`migration_template'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/bundler/gems/puffer-4b18186e8916/lib/generators/puffer/puffer_user/puffer_user_generator.rb:12:in `copy_flies'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`block in invoke_all'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `each'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/invocation.rb:124:in`map'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `invoke_all'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/group.rb:226:in`dispatch'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/railties-3.2.2/lib/rails/generators.rb:170:in`invoke'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/railties-3.2.2/lib/rails/commands/generate.rb:12:in `<top (required)>'
        from /home/proton/.rvm/gems/ruby-1.9.3-p0@onila/gems/railties-3.2.2/lib/rails/commands.rb:29:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by pyromaniac** [comment]
Ок, ты выкинул активрекорд из приложения вообще?

**Comment by proton** [comment]
Вроде как. По крайней мере сайт работает, если объекты через консоль добавлять

**Comment by pyromaniac** [comment]
Обновись ещё раз. Я сделал орм-зависимый генератор. Теперь оно тебе сгенерит модельки для монгойда.

**Comment by proton** [comment]
Да, заработало, спасибо!

**Comment by proton** [comment]
Так, ещё вопрос, как использовать devise?

создал app/controllers/admin/sessions_controller.rb

```
class Admin::SessionsController < Puffer::Sessions::Devise
end
```

http://localhost:3000/admin выдаёт

```
uninitialized constant Puffer::Sessions::Devise
```

**Comment by pyromaniac** [comment]
Это всё по одной простой причине ) https://github.com/puffer/puffer/blob/master/lib/puffer/backends/controllers/sessions/devise.rb - тут, к сожалению, пусто )
поэтому https://github.com/puffer/puffer/blob/master/lib/puffer.rb#L53 тут оно даже не объявлено в автолоад. Если есть возможность - напиши для девайса по образу и подобию. В геме есть даже shared example для спекования. https://github.com/puffer/puffer/blob/master/spec/controllers/sessions/clearance_spec.rb просто делай по аналогии и куча спеков для девайс контроллера одним движением.

**Comment by proton** [comment]
Хм, что-то поковырялся, так и не понял множество моментов :(
jabber свой не подскажешь?

**Comment by pyromaniac** [comment]
Я к тебе уже постучался. Или заходи на ruby@conference.jabber.ru

**Comment by gregwebs** [comment]
this issue is closed. does rails 3.2 work with puffer? The README says only 3.1

**Comment by proton** [comment]
Yes, it works :)

**Comment by mahemoff** [comment]
FYI the README says "It's compatible with Rails 3.1 only"

**Comment by pyromaniac** [comment]
Fixed, thanks
